name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      env:
        HOST: 52.74.240.16
        USER: ubuntu
      run: |
        ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd /path/to/your/project
          git pull origin main
          docker-compose down
          docker-compose up --build -d
        EOF
