name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: socialbot
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo 'export BUN_INSTALL="$HOME/.bun"' >> $GITHUB_ENV
        echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> $GITHUB_ENV
        echo 'source $HOME/.bashrc' >> $GITHUB_ENV
        source $HOME/.bashrc
        source $GITHUB_ENV
        bun --version

    - name: Install dependencies
      run: |
        source $HOME/.bashrc
        bun install

    - name: Lint code
      run: |
        source $HOME/.bashrc
        bun run lint

    - name: Build the project
      run: |
        source $HOME/.bashrc
        bun run build

    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/socialbot
      run: |
        source $HOME/.bashrc
        bun run test

  codeql:
    name: "CodeQL"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ] and ['swift', 'kotlin' ] for GitHub Enterprise Server
        # Learn more: https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code/configuring-the-codeql-workflow-for-compiled-languages

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Initializes the CodeQL tools for scanning.
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    # If the Autobuild fails, replace this step with manually built using the specific build tool
    # of your choice.
    # - run: |
    #     make bootstrap
    #     make release

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
